# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: XpertML
author: rookielittleblack
logo: assets/avatar.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/executablebooks/jupyter-book  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  extra_files: ['robots.txt', '.nojekyll']
  extra_navbar: |
    <script>
      // 添加随机参数到资源URL
      document.querySelectorAll('link[rel="stylesheet"], script[src]').forEach(el => {
        el.href = el.href + '?v=' + Date.now();
      });
    </script>

# 排除这些文件，使它们不会产生警告
exclude_patterns: [
  "README.md",  # 排除 README.md 文件
  "examples/*"  # 排除 examples 目录下的所有文件
]

latex:
  latex_documents:
    targetname: XpertML.tex
  latex_engine: xelatex
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: |
      \usepackage[UTF8]{ctex}
      \usepackage{xeCJK}
      % 禁用默认字体设置
      \defaultfontfeatures{}
      % 显式设置中文字体
      \setCJKmainfont[Path=/usr/share/fonts/opentype/noto/]{NotoSansCJK-Regular.ttc}[Language=Chinese]
      \setCJKsansfont[Path=/usr/share/fonts/opentype/noto/]{NotoSansCJK-Regular.ttc}[Language=Chinese]
      \setCJKmonofont[Path=/usr/share/fonts/opentype/noto/]{NotoSansCJK-Regular.ttc}[Language=Chinese]
      % 设置英文字体
      \setmainfont{DejaVu Serif}
      \setsansfont{DejaVu Sans}
      \setmonofont{DejaVu Sans Mono}
    babel: ''
    polyglossia: ''
    fontpkg: ''
    fncychap: ''
    maketitle: ''
    inputenc: ''
    cmappkg: ''
    fontenc: ''
    utf8extra: ''
    textcomp: ''
    geometry: \usepackage[a4paper,top=2.5cm,bottom=2.5cm,left=3cm,right=3cm]{geometry}
